### ISSUE TITLE
[BUG]Not working in Android 14

### ISSUE THREAD

**Issue by huajijam** [NextAlone/InstallerPlus#20]
Cannot debug because no developer has an Android 14 device
Xposed-Modules-Repo/ltd.nextalone.pkginstallerplus#1

**Comment by Loukious** [comment]
Seems to be working for me running Android 14 crDroid.
![Screenshot_20231025-105938_Package installer](https://github.com/NextAlone/InstallerPlus/assets/24696530/75378438-44a7-4d0f-bfe3-ce0c6deb40f9)
![Screenshot_20231025-110115_Settings](https://github.com/NextAlone/InstallerPlus/assets/24696530/9ee72a0e-7699-4090-85b9-ea6ef694e78b)

**Comment by huajijam** [comment]
> Seems to be working for me running Android 14 crDroid. ![Screenshot_20231025-105938_Package installer](https://user-images.githubusercontent.com/24696530/277953139-75378438-44a7-4d0f-bfe3-ce0c6deb40f9.png) ![Screenshot_20231025-110115_Settings](https://user-images.githubusercontent.com/24696530/277953299-9ee72a0e-7699-4090-85b9-ea6ef694e78b.png)

thx for ur feedback,we will close this issuses if devs got one Android14 device
