### ISSUE TITLE
Windows Defender mistakenly regards this software as a virus.

### ISSUE THREAD

**Issue by senzyo** [NextAlone/InstallerPlus#21]
It's not a big problem, but it's a bit annoying.

Windows Defender always treats this software as a viral software and removes it every time I download it, requiring me to manually restore it.

Is there any way to pass or escape checks from Windows Defender?

**Comment by huajijam** [comment]
![image](https://github.com/NextAlone/InstallerPlus/assets/29218242/4895000f-7ff9-41c4-81f6-42ddf68e8c64)
https://www.virustotal.com/gui/file/9f88fb33ca4f82957a7272039613f68eb140876432249809319852f8418c6fa7

**Comment by huajijam** [comment]
This is an **open source ANDROID** Xposed module and does not contain any viruses
**contact your system administrator for more information.**

**Comment by senzyo** [comment]
Yeah, of course I understand and trust this project. This is just a slightly comical problem, sorry for taking up your time.

**Comment by huajijam** [comment]
![badge](https://github.com/NextAlone/InstallerPlus/assets/29218242/1e246b8b-f7d7-49f4-bf4e-a8cc957764d7)
