### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by riyadmondol2006** [NextAlone/InstallerPlus#22]
Not working in
AP11.231117.006 Pixel 6

**Comment by riyadmondol2006** [comment]
https://drive.google.com/file/d/1zo7sNZClITqmGV_HxruGqe822kXYa6ad/view?usp=drivesdk

here is the apk file of package installer

**Comment by huajijam** [comment]
Please provide log

**Comment by huajijam** [comment]
fixed in #24
