### ISSUE TITLE
Stopped working with A14 March update

### ISSUE THREAD

**Issue by skirol** [NextAlone/InstallerPlus#23]
It completely stopped working with March update on Pixel 7 Pro stock A14.
It's been working perfectly until now.
Anyone else?

**Comment by jojobozo** [comment]
Same issue for me, Pixel 7

**Comment by ZanzDroid** [comment]
Will there be a new release with the fixed/updated code?

**Comment by Fishawyyy** [comment]
> Will there be a new release with the fixed/updated code?
> 
> I went ahead and compiled it, and it's working great.  Thanks!

Mind sharing the compiled one until an update is released?

**Comment by racnes** [comment]
same with A73 One UI 6.1 update

**Comment by skirol** [comment]
> same with A73 One UI 6.1 update

go to https://github.com/NextAlone/InstallerPlus/actions/runs/8739993829 scroll all the way down and click on InstallerPlus-debug-51a87ab

**Comment by racnes** [comment]
> > same with A73 One UI 6.1 update
> 
> go to https://github.com/NextAlone/InstallerPlus/actions/runs/8739993829 scroll all the way down and click on InstallerPlus-debug-51a87ab

tank you, now its working fine
