### ISSUE TITLE
[Wish] Remove/skip first dialog please

### ISSUE THREAD

**Issue by drakulaboy** [NextAlone/InstallerPlus#8]
module is working great on Android 12, a small wish can you please remove/skip this dialog wich appear first when i want to install a apk
![screenshot 2021-11-28 001](https://user-images.githubusercontent.com/7822898/143770197-b1cd896f-f7a1-4786-a709-8f2f46b8404e.png)
thank you!

**Comment by NextAlone** [comment]
i don't have this dialog, you can provide your installer here, so i will see how it works

**Comment by drakulaboy** [comment]
usually this pops out when i install downloaded apk's, here is the Packagage Installer from my phone and a downloaded apk
[files.zip](https://github.com/NextAlone/InstallerPlus/files/7613876/files.zip)
 thank you very much, i like this module a lot!

**Comment by NextAlone** [comment]
@drakulaboy Check whether there is a switch to verify unknown sources in the security section of the settings.

**Comment by drakulaboy** [comment]
@NextAlone i found the cause, isee a behavior, this popup dialog appears only in the stock firmware file browser, if i install apk's from other file managers there is no popup, but this String with "Your phone blablabla" it's in the PackageInstaller, 
![screenshot 2021-11-29 001](https://user-images.githubusercontent.com/7822898/143830720-5d6d025e-e23f-4cf3-b48d-5879d7732330.png) , anyway i'm using other File Manager and there is everything ok so thank you for this awesome module!

**Comment by NextAlone** [comment]
@drakulaboy OK cheers!
